name: Build Android APK
on:
  workflow_dispatch:
    inputs:
      params:
        type: string
        description: Build Params
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        if: ${{ fromJSON(github.event.inputs.params).java != '' }}
        with:
          java-version: ${{ fromJSON(github.event.inputs.params).java }}
          distribution: corretto
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        if: ${{ fromJSON(github.event.inputs.params).node != '' }}
        with:
          node-version: ${{ fromJSON(github.event.inputs.params).node }}
      - name: Setup Android NDK
        if: ${{ fromJSON(github.event.inputs.params).ndk != '' }}
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r21
          add-to-path: true
          link-to-sdk: true
          local-cache: true
      - name: Clone Repo
        run: git clone --depth=1 --single-branch --branch=${{ fromJSON(github.event.inputs.params).branch }} https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@${{ fromJSON(github.event.inputs.params).repo }} input
      - name: Get Apps Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./input
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./input/node_modules
          key: node_modules-${{hashFiles('input/yarn.lock')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current yarn.lock
      - name: Yarn Install
        working-directory: input
        run: yarn install
      - name: Gradle Build
        working-directory: input/android
        run: ./gradlew assemble${{ fromJSON(github.event.inputs.params).flavor }}${{ fromJSON(github.event.inputs.params).configuration }}
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ fromJSON(github.event.inputs.params).releaseTo }}
          token: ${{ secrets.GH_PAT }}
          files: |
            input/**/*.apk
          tag_name: "v${{ steps.package-version.outputs.current-version}}-${{ fromJSON(github.event.inputs.params).configuration }}-${{ fromJSON(github.event.inputs.params).branch }}"
          body: "IPA Release v${{ steps.package-version.outputs.current-version}} (${{ fromJSON(github.event.inputs.params).configuration }})"
          body_path: ./input/releasenote.md
