name: Build Android APK
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        description: Repo to pull
        required: true
      branch:
        type: string
        description: Source Branch
        default: master
        required: true
      flavor:
        type: string
        description: Build Flavor
      configuration:
        type: choice
        description: Build Configuration
        options: 
          - Release
          - Debug
      tags:
        type: string
        description: Release Tag
      releaseTo:
        type: string
        description: Release To Repo
      java:
        type: string
        description: Java Version
      node:
        type: string
        description: NodeJS Version
      ndk:
        type: string
        description: NDK Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        if: ${{ github.event.inputs.java != '' }}
        with:
          java-version: ${{ github.event.inputs.java }}
          distribution: corretto
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        if: ${{ github.event.inputs.node != '' }}
        with:
          node-version: ${{ github.event.inputs.node }}
      - name: Setup Android NDK
        if: ${{ github.event.inputs.ndk != '' }}
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r21
          add-to-path: true
          link-to-sdk: true
          local-cache: true
      - name: Clone Repo
        run: git clone --depth=1 --single-branch --branch=${{ github.event.inputs.branch }} https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@${{ github.event.inputs.repo }} input
      - name: Yarn Install
        working-directory: input
        run: yarn install
      - name: Gradle Build
        working-directory: input/android
        run: ./gradlew assemble${{ github.event.inputs.flavor }}${{ github.event.inputs.configuration }}
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ github.event.inputs.releaseTo }}
          token: ${{ secrets.GH_PAT }}
          files: |
            input/**/*.apk
          tag_name: "v${{ github.event.inputs.tags }}"
          body: "APK Release v${{ github.event.inputs.tags }} (${{ github.event.inputs.configuration }})"
          append_body: true
          file: input/**/*.apk
