name: Delete old workflow runs
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          curl -L -X POST \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          https://${{ secrets.APPCENTER_DOMAIN }}/projects/wfcleaner/trigger-log?wf_id=${{ github.run_id }}
      - name: Delete workflow runs
        run: |
          curl -L -X GET \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          https://${{ secrets.APPCENTER_DOMAIN }}/workflow-clean
