name: Build iOS IPA
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        description: Repo to pull
        required: true
      branch:
        type: string
        description: Source Branch
      configuration:
        type: choice
        description: Build Configuration
        options: 
          - Release
          - Debug
      tags:
        type: string
        description: Release Tag
      releaseTo:
        type: string
        description: Release To Repo
      node:
        type: string
        description: NodeJS Version
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        if: ${{ github.event.inputs.node != '' }}
        with:
          node-version: ${{ github.event.inputs.node }}
      - name: Clone Repo
        run: git clone --depth=1 --single-branch --branch=${{ github.event.inputs.branch }} https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@${{ github.event.inputs.repo }} input
      - name: Yarn Install
        working-directory: input
        run: yarn install
      - name: Pod Repo
        run: pod repo add QuadrantSpecs https://oktapod.quadrant-si.id/framework/quadrant.specs.git
      - name: Pod install
        working-directory: input/ios
        run: pod install
      - name: Download Export Plist
        run: curl --output export.plist "https://appcenterq.vercel.app/ios-export"
      - name: Build IPA
        uses: muhamad-rizki/ios-build-action@v1.0.1
        with:
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          project-path: input/ios/MZPro.xcodeproj
          workspace-path: input/ios/MZPro.xcworkspace
          scheme: MZPro
          configuration: ${{ github.event.inputs.configuration }}
          export-method: ad-hoc
          output-path: "output-${{ github.event.inputs.configuration }}.ipa"
          export-options: export.plist
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ github.event.inputs.releaseTo }}
          token: ${{ secrets.GH_PAT }}
          files: |
            "output-${{ github.event.inputs.configuration }}.ipa"
            "manifest.plist"
          tag_name: "v${{ github.event.inputs.tags }}-${{ github.event.inputs.configuration }}"
          body: "IPA Release v${{ github.event.inputs.tags }} (${{ github.event.inputs.configuration }})"
          append_body: true
