name: Repack and Release

on:
  workflow_dispatch:
    inputs:
      params:
        type: string
        description: Build Params (JSON)
        required: true

jobs:
  repack-android:
    name: Repack APK
    runs-on: macos-latest
    if: ${{ fromJSON(github.event.inputs.params).platform == 'android' }}
    steps:
      - name: Checkout Workflow Scripts
        uses: actions/checkout@v4

      - name: Clone Source Repo
        run: |
          git clone --depth=1 --single-branch \
            --branch=${{ fromJSON(github.event.inputs.params).branch }} \
            https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@${{ fromJSON(github.event.inputs.params).repo }} \
            input

      - name: Get App Version
        id: package-version
        working-directory: input
        run: |
          current_version=$(node -e "console.log(require('./package.json').version)")
          echo "current-version=$current_version" >> "$GITHUB_OUTPUT"

      - name: Logging
        run: |
          curl -s -L -G -X POST \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          --data-urlencode 'wf_id=${{ github.run_id }}' \
          --data-urlencode 'params=${{ github.event.inputs.params }}' \
          --data-urlencode 'uniqueId=${{ fromJSON(github.event.inputs.params).uniqueId }}' \
          --data-urlencode 'version=${{ steps.package-version.outputs.current-version }}' \
          --data-urlencode 'platform=android' \
          https://${{ secrets.APPCENTER_DOMAIN }}/projects/${{ fromJSON(github.event.inputs.params).projectid }}/trigger-log

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        if: ${{ fromJSON(github.event.inputs.params).java != '' }}
        with:
          java-version: ${{ fromJSON(github.event.inputs.params).java }}
          distribution: corretto

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        if: ${{ fromJSON(github.event.inputs.params).node != '' }}
        with:
          node-version: ${{ fromJSON(github.event.inputs.params).node }}

      - name: Initialize Watchman
        uses: ConorMacBride/install-package@v1
        with:
          brew: watchman

      - name: Yarn Install
        working-directory: input
        run: yarn install

      - name: Mask Sensitive Values
        run: |
          echo "::add-mask::${{ fromJSON(github.event.inputs.params).keystorePassword }}"
          echo "::add-mask::${{ fromJSON(github.event.inputs.params).keyPassword }}"

      - name: Repack and Sign APK
        env:
          CI: "true"
          WORK_DIR: ${{ github.workspace }}
          SOURCE_DIR: ${{ github.workspace }}/input
          BUNDLE_OUTPUT_DIR: ${{ github.workspace }}/bundle_output
          RELEASE_DOWNLOAD_DIR: ${{ github.workspace }}/release_download
          RELEASE_REPO: ${{ fromJSON(github.event.inputs.params).releaseRepo }}
          RELEASE_TAG: ${{ fromJSON(github.event.inputs.params).releaseTag }}
          APK_FILENAME: ${{ fromJSON(github.event.inputs.params).apkFilename || '*.apk' }}
          KEYSTORE_PATH: ${{ fromJSON(github.event.inputs.params).keystorePath }}
          KEYSTORE_PASSWORD: ${{ fromJSON(github.event.inputs.params).keystorePassword }}
          KEY_ALIAS: ${{ fromJSON(github.event.inputs.params).keyAlias }}
          KEY_PASSWORD: ${{ fromJSON(github.event.inputs.params).keyPassword }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          APP_VERSION: ${{ steps.package-version.outputs.current-version }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ fromJSON(github.event.inputs.params).sentryProject || '' }}
        run: bash scripts/repack_android.sh

      - name: Upload to Release
        id: release
        uses: muhamad-rizki/action-gh-release@v3.0.1
        with:
          repository: ${{ fromJSON(github.event.inputs.params).releaseTo }}
          token: ${{ secrets.GH_PAT }}
          files: release_download/resigned-output.apk
          tag_name: "v${{ steps.package-version.outputs.current-version }}-${{ fromJSON(github.event.inputs.params).configuration }}-${{ fromJSON(github.event.inputs.params).branch }}"
          body: "Repacked APK v${{ steps.package-version.outputs.current-version }} (${{ fromJSON(github.event.inputs.params).configuration }})"
          body_path: ./input/${{ fromJSON(github.event.inputs.params).releasenote != '' && fromJSON(github.event.inputs.params).releasenote || 'releasenote.md' }}

      - name: Update DB
        run: |
          curl -s -L -X POST \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          https://${{ secrets.APPCENTER_DOMAIN }}/projects/${{ fromJSON(github.event.inputs.params).projectid }}/release?id=${{ steps.release.outputs.id }}

  repack-ios:
    name: Repack IPA
    runs-on: macos-14
    if: ${{ fromJSON(github.event.inputs.params).platform == 'ios' }}
    steps:
      - name: Checkout Workflow Scripts
        uses: actions/checkout@v4

      - name: Clone Source Repo
        run: |
          git clone --depth=1 --single-branch \
            --branch=${{ fromJSON(github.event.inputs.params).branch }} \
            https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@${{ fromJSON(github.event.inputs.params).repo }} \
            input

      - name: Clone Provision Repo
        run: |
          git clone --depth=1 --single-branch --branch=main \
            https://admindevopsqsi:${{ secrets.GH_PAT }}@github.com/admindevopsqsi/ios-provision.git \
            provision

      - name: Get App Version
        id: package-version
        working-directory: input
        run: |
          current_version=$(node -e "console.log(require('./package.json').version)")
          echo "current-version=$current_version" >> "$GITHUB_OUTPUT"

      - name: Logging
        run: |
          curl -s -L -G -X POST \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          --data-urlencode 'wf_id=${{ github.run_id }}' \
          --data-urlencode 'params=${{ github.event.inputs.params }}' \
          --data-urlencode 'uniqueId=${{ fromJSON(github.event.inputs.params).uniqueId }}' \
          --data-urlencode 'version=${{ steps.package-version.outputs.current-version }}' \
          --data-urlencode 'platform=ios' \
          https://${{ secrets.APPCENTER_DOMAIN }}/projects/${{ fromJSON(github.event.inputs.params).projectid }}/trigger-log

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        if: ${{ fromJSON(github.event.inputs.params).node != '' }}
        with:
          node-version: ${{ fromJSON(github.event.inputs.params).node }}

      - name: Install & Cache Watchman
        uses: ConorMacBride/install-package@v1
        with:
          brew: watchman

      - name: Yarn Install
        working-directory: input
        run: yarn install

      - name: Mask Sensitive Values
        run: |
          echo "::add-mask::${{ fromJSON(github.event.inputs.params).p12pass }}"

      - name: Repack and Sign IPA
        env:
          CI: "true"
          WORK_DIR: ${{ github.workspace }}
          SOURCE_DIR: ${{ github.workspace }}/input
          PROVISION_DIR: ${{ github.workspace }}/provision
          BUNDLE_OUTPUT_DIR: ${{ github.workspace }}/bundle_output
          RELEASE_DOWNLOAD_DIR: ${{ github.workspace }}/release_download
          RELEASE_REPO: ${{ fromJSON(github.event.inputs.params).releaseRepo }}
          RELEASE_TAG: ${{ fromJSON(github.event.inputs.params).releaseTag }}
          IPA_FILENAME: ${{ fromJSON(github.event.inputs.params).ipaFilename || '*.ipa' }}
          PROJECT_ID: ${{ fromJSON(github.event.inputs.params).projectid }}
          PROVISION_FILE: ${{ fromJSON(github.event.inputs.params).provisionfile != '' && fromJSON(github.event.inputs.params).provisionfile || fromJSON(github.event.inputs.params).branch }}
          P12_PASSWORD: ${{ fromJSON(github.event.inputs.params).p12pass || '' }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          APP_VERSION: ${{ steps.package-version.outputs.current-version }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ fromJSON(github.event.inputs.params).sentryProject || '' }}
        run: bash scripts/repack_ios.sh

      - name: Upload to Release
        id: release
        uses: muhamad-rizki/action-gh-release@v3.0.1
        with:
          repository: ${{ fromJSON(github.event.inputs.params).releaseTo }}
          token: ${{ secrets.GH_PAT }}
          files: release_download/resigned-output.ipa
          tag_name: "v${{ steps.package-version.outputs.current-version }}-${{ fromJSON(github.event.inputs.params).configuration }}-${{ fromJSON(github.event.inputs.params).branch }}"
          body: "Repacked IPA v${{ steps.package-version.outputs.current-version }} (${{ fromJSON(github.event.inputs.params).configuration }})"
          body_path: ./input/${{ fromJSON(github.event.inputs.params).releasenote != '' && fromJSON(github.event.inputs.params).releasenote || 'releasenote.md' }}

      - name: Update DB
        run: |
          curl -s -L -X POST \
          -H "X-AppCenter-Secret: ${{ secrets.APPCENTER_SECRET }}" \
          https://${{ secrets.APPCENTER_DOMAIN }}/projects/${{ fromJSON(github.event.inputs.params).projectid }}/release?id=${{ steps.release.outputs.id }}
